### ISSUE TITLE
Sofia-sip.rb out of date causes build failure. Needs update to 1.13.6

### ISSUE THREAD

**Issue by MarioG-X** [signalwire/homebrew-signalwire#3]
Title says it: Sofia-sip-rb out of date causes build failure. Needs update to 1.13.6, Causes https://github.com/signalwire/freeswitch/issues/1400

**Comment by andywolk** [comment]
How about this https://github.com/signalwire/homebrew-signalwire/pull/2

**Comment by MarioG-X** [comment]
I think "How about this #2" means did I test, not yet since the homebrew formula is not changed yet:
https://github.com/signalwire/homebrew-signalwire/blob/master/Formula/libks.rb

**Comment by andywolk** [comment]
https://github.com/signalwire/homebrew-signalwire/pull/5

**Comment by andywolk** [comment]
Merged.

**Comment by MarioG-X** [comment]
Testing everything now
