### ISSUE TITLE
signalwire-c.rb out of date causes build failure. Needs update to 1.2.0

### ISSUE THREAD

**Issue by MarioG-X** [signalwire/homebrew-signalwire#6]
signalwire-c.rb out of date causes build failure. Needs update to 1.2.0
I _think_ this is causing the error below which is preventing testing of other issue fixes:

/lib /usr/local/Cellar/libks/1.7.1/lib/libks.1.dylib /usr/local/opt/openssl@3/lib/libssl.dylib /usr/local/opt/openssl@3/lib/libcrypto.dylib 
Undefined symbols for architecture x86_64:
  "_ks_rng_get_uint32", referenced from:
      _swclt_store_select_random_protocol_provider in nodestore.c.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [libsignalwire_client.1.dylib] Error 1
make[1]: *** [CMakeFiles/signalwire_client.dir/all] Error 2
make: *** [all] Error 2

**Comment by andywolk** [comment]
https://github.com/signalwire/homebrew-signalwire/pull/7
